# Generated by Django 5.2 on 2025-05-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('born_date', models.DateField(verbose_name='born date')),
                ('die_date', models.DateField(blank=True, null=True, verbose_name='Die date')),
                ('Profession', models.CharField(max_length=50, verbose_name='Profession')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'actors',
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Frasedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.TextField(max_length=400, verbose_name='appointment')),
                ('autor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.autordb')),
            ],
        ),
    ]
