# Generated by Django 5.2 on 2025-05-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasedb',
            name='autor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases', to='amm.autordb'),
        ),
    ]
